[workspace]
members = [
    "node", "pallets/double-map", "pallets/map-set", 
    "pallets/storage-cache", "pallets/struct-storage",
    "pallets/template", "pallets/vec-set",
    "runtime", "traits/account-set",
]
[profile.release]
panic = "unwind"
